 export const defaultVisibility={
      q1mesecni: false,
      q1dl1: false,
      q1ios: false,
      q1porezNaDobit: false,
      q1pdv: false,
      q2porezNaDobit: false,
      q2pdv: false,
      q2ios: false,
      q2dl1: false,
      q2msecni: false,
      q2lpa: false,
      q2lpaFirm: false,
    }
   export  const Q2={
        q1mesecni: false,
        q1dl1: false,
        q1ios: false,
        q1porezNaDobit: false,
        q1pdv: false,
        q2porezNaDobit: true,
        q2pdv: true,
        q2ios: true,
        q2dl1: true,
        q2msecni: true,
        q2lpa: true,
        q2lpaFirm: true,
      }
    export const Q1={
        q1mesecni: true,
        q1dl1: true,
        q1ios: true,
        q1porezNaDobit: true,
        q1pdv: true,
        q2porezNaDobit: false,
        q2pdv: false,
        q2ios: false,
        q2dl1: false,
        q2msecni: false,
        q2lpa: false,
        q2lpaFirm: false,
      }